# Generated by Django 3.0.5 on 2020-05-04 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('math_test_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemheaditem',
            options={'verbose_name': 'Problem head item', 'verbose_name_plural': 'Problem head items'},
        ),
        migrations.AlterModelOptions(
            name='problempointitem',
            options={'verbose_name': "answer on problem's point", 'verbose_name_plural': "answers on problem's points"},
        ),
    ]
