# Generated by Django 3.0.5 on 2020-05-06 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problemheaditem',
            old_name='problem_head_id',
            new_name='problem_head',
        ),
        migrations.RenameField(
            model_name='problemheaditem',
            old_name='test_id',
            new_name='test',
        ),
        migrations.RenameField(
            model_name='problempointitem',
            old_name='problem_item_id',
            new_name='problem_item',
        ),
        migrations.RenameField(
            model_name='prototype2test',
            old_name='set_id',
            new_name='set',
        ),
        migrations.RenameField(
            model_name='prototype2test',
            old_name='test_id',
            new_name='test',
        ),
        migrations.RenameField(
            model_name='testitem',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='testitem',
            old_name='template_id',
            new_name='template',
        ),
    ]
