# Generated by Django 3.0.5 on 2020-05-06 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200506_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemheaditem',
            options={'verbose_name': 'Problem head item', 'verbose_name_plural': 'Problem head items'},
        ),
        migrations.AlterModelOptions(
            name='problempointitem',
            options={'verbose_name': "answer on problem's point", 'verbose_name_plural': "answers on problem's points"},
        ),
    ]
