# Generated by Django 3.0.6 on 2020-05-10 11:04

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200506_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemprototype',
            name='description',
            field=models.TextField(blank=True, default='No description yet'),
        ),
        migrations.CreateModel(
            name='UserSolutionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=api.models.rename_file_on_upload)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ProblemPointItem')),
            ],
            options={
                'verbose_name': "user's solution file",
                'verbose_name_plural': "user's solution files",
            },
        ),
    ]
