# Generated by Django 3.0.5 on 2020-05-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200510_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problempointitem',
            name='score',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
